# apply_borg_struct.py  --  run in Ghidra Script Manager (Ghidra 12 / Python 3 via pyghidra)
# Creates (idempotently) BorgInstance and types the borg param of known borg functions.
# Auto-generated by gen_borg_struct.py from the documented struct-offset research.
from ghidra.program.model.data import (StructureDataType, CategoryPath, PointerDataType,
    FloatDataType, DoubleDataType, ByteDataType, ShortDataType, IntegerDataType,
    DataTypeConflictHandler)
from ghidra.program.model.listing import ParameterImpl
from ghidra.program.model.symbol import SourceType

STRUCT_NAME = "BorgInstance"
SIZE = 0x1de0
FIELDS = [
    (0x1c, 'field_01c', 'short', 2),
    (0x24, 'field_024', 'float', 4),
    (0x30, 'field_030', 'float', 4),
    (0x41, 'field_041', 'byte', 1),
    (0x44, 'pos_x', 'float', 4),
    (0x48, 'pos_y', 'float', 4),
    (0x4c, 'pos_z', 'float', 4),
    (0x50, 'field_050', 'float', 4),
    (0x58, 'vel_x', 'float', 4),
    (0x5c, 'vel_y', 'float', 4),
    (0x60, 'vel_z', 'float', 4),
    (0x6c, 'scale_or_radius', 'float', 4),
    (0x72, 'heading_yaw', 'short', 2),
    (0x7c, 'aux_angle_a', 'short', 2),
    (0x7e, 'aux_angle_b', 'short', 2),
    (0x80, 'aux_angle_c', 'short', 2),
    (0x82, 'field_082', 'byte', 1),
    (0x87, 'field_087', 'byte', 1),
    (0x96, 'field_096', 'byte', 1),
    (0xb4, 'frame_scalar_0b4', 'float', 4),
    (0x190, 'flag_190', 'byte', 1),
    (0x272, 'invinc_flag', 'short', 2),
    (0x284, 'base_id', 'short', 2),
    (0x3f3, 'field_3f3', 'byte', 1),
    (0x4ac, 'field_4ac', 'int', 4),
    (0x4b0, 'field_4b0', 'int', 4),
    (0x540, 'state_540', 'byte', 1),
    (0x541, 'substate_541', 'byte', 1),
    (0x544, 'action_state', 'byte', 1),
    (0x545, 'field_545', 'byte', 1),
    (0x550, 'substate_550', 'short', 2),
    (0x552, 'substate_timer', 'short', 2),
    (0x568, 'aim_x', 'float', 4),
    (0x56c, 'aim_y', 'float', 4),
    (0x570, 'aim_z', 'float', 4),
    (0x57c, 'field_57c', 'byte', 1),
    (0x57d, 'field_57d', 'byte', 1),
    (0x590, 'field_590', 'byte', 1),
    (0x591, 'attack_selector', 'byte', 1),
    (0x5aa, 'facing_angle_a', 'short', 2),
    (0x5ac, 'facing_angle_b', 'short', 2),
    (0x5ae, 'facing_angle_c', 'short', 2),
    (0x5b0, 'field_5b0', 'short', 2),
    (0x5b4, 'field_5b4', 'int', 4),
    (0x5e0, 'status_flags', 'int', 4),
    (0x5ec, 'field_5ec', 'float', 4),
    (0x656, 'field_656', 'byte', 1),
    (0x668, 'field_668', 'float', 4),
    (0x690, 'field_690', 'float', 4),
    (0x69c, 'field_69c', 'float', 4),
    (0x6b4, 'anim_subflag', 'short', 2),
    (0x6b6, 'field_6b6', 'short', 2),
    (0x6d0, 'field_6d0', 'float', 4),
    (0x6fd, 'field_6fd', 'byte', 1),
    (0x6fe, 'field_6fe', 'byte', 1),
    (0x709, 'field_709', 'byte', 1),
    (0x71b, 'field_71b', 'byte', 1),
    (0x720, 'invinc_timer', 'float', 4),
    (0x734, 'field_734', 'short', 2),
    (0x754, 'field_754', 'int', 4),
    (0x7c9, 'field_7c9', 'byte', 1),
    (0x7de, 'field_7de', 'byte', 1),
    (0x8c4, 'field_8c4', 'int', 4),
    (0x18da, 'field_18da', 'short', 2),
    (0x18dc, 'field_18dc', 'short', 2),
    (0x18de, 'field_18de', 'short', 2),
    (0x1b38, 'field_1b38', 'short', 2),
    (0x1cef, 'field_1cef', 'byte', 1),
    (0x1cf0, 'render_mode', 'byte', 1),
    (0x1d0e, 'input_byte_0', 'byte', 1),
    (0x1d0f, 'input_byte_1', 'byte', 1),
    (0x1d10, 'input_byte_2', 'byte', 1),
    (0x1d9c, 'field_1d9c', 'float', 4),
    (0x1dbc, 'field_1dbc', 'float', 4),
    (0x1dc4, 'field_1dc4', 'float', 4),
    (0x1dc8, 'phys_scalar_1dc8', 'float', 4),
    (0x1dcc, 'frame_step', 'float', 4),
    (0x1dd4, 'phys_scalar_1dd4', 'float', 4),
]
BORG_FUNCS = ['8005cc00', '8005d494', '80055c00', '800670dc', '80066ec0', '80066f1c', '8005f188', '8004cd24', '80046510', '800677b0', '8005ec04', '8005f114', '80067310', '8005ed38']

TYPES = {"float": FloatDataType(), "double": DoubleDataType(), "byte": ByteDataType(),
         "short": ShortDataType(), "int": IntegerDataType()}

dtm = currentProgram.getDataTypeManager()
struct = StructureDataType(CategoryPath("/GotchaForce"), STRUCT_NAME, SIZE)
placed = 0
for off, name, tname, sz in FIELDS:
    try:
        struct.replaceAtOffset(off, TYPES[tname], sz, name, "")
        placed += 1
    except Exception as e:
        print("  skip 0x%x %s: %s" % (off, name, e))

tx = currentProgram.startTransaction("create BorgInstance")
try:
    existing = dtm.getDataType(CategoryPath("/GotchaForce"), STRUCT_NAME)
    if existing is not None:
        dtm.remove(existing, monitor)   # idempotent: drop the prior version first
    dt = dtm.addDataType(struct, DataTypeConflictHandler.REPLACE_HANDLER)
finally:
    currentProgram.endTransaction(tx, True)
print("Created %s (%d bytes, %d fields)" % (STRUCT_NAME, SIZE, placed))

ptr = PointerDataType(dt)
fm = currentProgram.getFunctionManager()
tx = currentProgram.startTransaction("apply BorgInstance*")
typed = 0
try:
    for a in BORG_FUNCS:
        f = fm.getFunctionAt(toAddr(a))          # toAddr parses the hex string directly
        if f is None:
            print("  no function at " + a); continue
        try:
            if f.getParameterCount() == 0:
                f.addParameter(ParameterImpl("actor", ptr, currentProgram), SourceType.USER_DEFINED)
            else:
                f.getParameter(0).setDataType(ptr, SourceType.USER_DEFINED)
                f.getParameter(0).setName("actor", SourceType.USER_DEFINED)
            typed += 1
        except Exception as e:
            print("  apply fail " + a + ": " + str(e))
finally:
    currentProgram.endTransaction(tx, True)
print("Applied BorgInstance* to %d/%d functions" % (typed, len(BORG_FUNCS)))
