"""
Generate a Ghidra script that creates the `BorgInstance` struct (from the documented
struct-offset research) and applies it to the known borg-handling functions, so decompiled
code shows `actor->action_state` instead of `*(char*)(actor+0x544)`.

Sources:
  - research/decomp/borg-struct-offsets.txt   (offset, width, r, w, kind — the layout)
  - curated field names below                 (from behavior-notes.md section 3)

The Ghidra MCP has no create-struct endpoint, so this emits a script the user runs once via
Ghidra's Script Manager. Output: apply_borg_struct.py
"""
import os, re

RROOT = r"D:\GotYaForce\research"
OFFS_TXT = os.path.join(RROOT, "decomp", "borg-struct-offsets.txt")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "apply_borg_struct.py")

# Curated names for the documented offsets (behavior-notes.md §3). Everything else becomes
# field_0xNNN with a type inferred from the harvested width/kind.
NAMED = {
    0x044: "pos_x", 0x048: "pos_y", 0x04c: "pos_z",
    0x058: "vel_x", 0x05c: "vel_y", 0x060: "vel_z",
    0x06c: "scale_or_radius",
    0x072: "heading_yaw",
    0x07c: "aux_angle_a", 0x07e: "aux_angle_b", 0x080: "aux_angle_c",
    0x0b4: "frame_scalar_0b4",
    0x190: "flag_190",
    0x272: "invinc_flag",
    0x284: "base_id",
    0x540: "state_540", 0x541: "substate_541",  # provisional: the 0x800c dispatch chain keys on 0x540
    0x544: "action_state",
    0x550: "substate_550", 0x552: "substate_timer",
    0x568: "aim_x", 0x56c: "aim_y", 0x570: "aim_z",
    0x591: "attack_selector",
    0x5aa: "facing_angle_a", 0x5ac: "facing_angle_b", 0x5ae: "facing_angle_c",
    0x5e0: "status_flags",
    0x6b4: "anim_subflag",
    0x720: "invinc_timer",
    0x1cf0: "render_mode",
    0x1d0e: "input_byte_0", 0x1d0f: "input_byte_1", 0x1d10: "input_byte_2",
    0x1dc8: "phys_scalar_1dc8", 0x1dcc: "frame_step", 0x1dd4: "phys_scalar_1dd4",
}

# Borg-handling functions (r3 = BorgInstance*). From behavior-notes.md §4 + the state-machine
# range. param 0 gets typed to BorgInstance*.
BORG_FUNCS = [
    "8005cc00", "8005d494", "80055c00", "800670dc", "80066ec0", "80066f1c",
    "8005f188", "8004cd24", "80046510", "800677b0", "8005ec04", "8005f114",
    "80067310", "8005ed38",
]

def gtype(kind, width):
    if kind == "float":
        return ("float", 4) if width == 4 else ("double", 8) if width == 8 else ("float", 4)
    return {1: ("byte", 1), 2: ("short", 2), 4: ("int", 4)}.get(width, ("byte", 1))

def load_fields():
    fields = {}
    for ln in open(OFFS_TXT, encoding="utf-8", errors="ignore"):
        m = re.match(r"\s*0x([0-9a-fA-F]+)\s+(\d+)\s+\d+\s+\d+\s+(\w+)", ln)
        if not m:
            continue
        off = int(m.group(1), 16)
        width = int(m.group(2))
        kind = m.group(3)
        tname, size = gtype(kind, width)
        name = NAMED.get(off, "field_%03x" % off)
        fields[off] = (name, tname, size)
    # ensure all curated offsets exist even if absent from the harvest
    for off, name in NAMED.items():
        fields.setdefault(off, (name, "int", 2))
    # force single-byte type for state bytes so they don't overlap neighbours
    for off in (0x540, 0x541):
        if off in fields:
            fields[off] = (fields[off][0], "byte", 1)
    return dict(sorted(fields.items()))

def main():
    fields = load_fields()
    size = max(o + s for o, (_, _, s) in fields.items())
    size = (size + 0xF) & ~0xF
    field_lines = ",\n".join(
        "    (0x%x, %r, %r, %d)" % (o, n, t, s) for o, (n, t, s) in fields.items()
    )
    script = '''# apply_borg_struct.py  --  run in Ghidra Script Manager (Ghidra 12 / Python 3 via pyghidra)
# Creates (idempotently) BorgInstance and types the borg param of known borg functions.
# Auto-generated by gen_borg_struct.py from the documented struct-offset research.
from ghidra.program.model.data import (StructureDataType, CategoryPath, PointerDataType,
    FloatDataType, DoubleDataType, ByteDataType, ShortDataType, IntegerDataType,
    DataTypeConflictHandler)
from ghidra.program.model.listing import ParameterImpl
from ghidra.program.model.symbol import SourceType

STRUCT_NAME = "BorgInstance"
SIZE = 0x%x
FIELDS = [
%s,
]
BORG_FUNCS = %r

TYPES = {"float": FloatDataType(), "double": DoubleDataType(), "byte": ByteDataType(),
         "short": ShortDataType(), "int": IntegerDataType()}

dtm = currentProgram.getDataTypeManager()
struct = StructureDataType(CategoryPath("/GotchaForce"), STRUCT_NAME, SIZE)
placed = 0
for off, name, tname, sz in FIELDS:
    try:
        struct.replaceAtOffset(off, TYPES[tname], sz, name, "")
        placed += 1
    except Exception as e:
        print("  skip 0x%%x %%s: %%s" %% (off, name, e))

tx = currentProgram.startTransaction("create BorgInstance")
try:
    existing = dtm.getDataType(CategoryPath("/GotchaForce"), STRUCT_NAME)
    if existing is not None:
        dtm.remove(existing, monitor)   # idempotent: drop the prior version first
    dt = dtm.addDataType(struct, DataTypeConflictHandler.REPLACE_HANDLER)
finally:
    currentProgram.endTransaction(tx, True)
print("Created %%s (%%d bytes, %%d fields)" %% (STRUCT_NAME, SIZE, placed))

ptr = PointerDataType(dt)
fm = currentProgram.getFunctionManager()
tx = currentProgram.startTransaction("apply BorgInstance*")
typed = 0
try:
    for a in BORG_FUNCS:
        f = fm.getFunctionAt(toAddr(a))          # toAddr parses the hex string directly
        if f is None:
            print("  no function at " + a); continue
        try:
            if f.getParameterCount() == 0:
                f.addParameter(ParameterImpl("actor", ptr, currentProgram), SourceType.USER_DEFINED)
            else:
                f.getParameter(0).setDataType(ptr, SourceType.USER_DEFINED)
                f.getParameter(0).setName("actor", SourceType.USER_DEFINED)
            typed += 1
        except Exception as e:
            print("  apply fail " + a + ": " + str(e))
finally:
    currentProgram.endTransaction(tx, True)
print("Applied BorgInstance* to %%d/%%d functions" %% (typed, len(BORG_FUNCS)))
''' % (size, field_lines, BORG_FUNCS)
    open(OUT, "w", encoding="utf-8").write(script)
    print("Wrote %s" % OUT)
    print("Struct size: 0x%x (%d fields, %d named)" % (size, len(fields), sum(1 for o in fields if o in NAMED)))
    print("Named fields sample:")
    for o, (n, t, s) in list(fields.items())[:14]:
        print("  +0x%-4x %-6s %s" % (o, t, n))

if __name__ == "__main__":
    main()
