// =============================================================================
// gx_wgpipe_e2e_proof.mjs -- does a LOWERED ROM UNIT actually submit a vertex?
//
// Usage: node tools/gx_wgpipe_e2e_proof.mjs <assembly.wasm>
//
// Input is a module the assembly gate produced with write-gather-pipe lowering
// ON, containing the ROM's own draw function `zz_0027c34_` (chunk_0003.c:
// 3285-3328, verbatim out of the decompiled export). This script instantiates
// it, wires its `__gf_gx_wgpipe_*` imports to the REAL browser HLE host decode
// side (packages/rom-runtime/src/gx/{state,fifo,backend}.ts -- imported, not
// reimplemented), runs the function, and checks what the host assembled.
//
// This closes the seam docs/gx-hle-host.md section 7.1 named as blocker #1:
// "nothing downstream matters until a real ROM unit can submit a vertex."
//
// IT CARRIES NO BEHAVIOURAL CLAIM about the resulting frame. Section 1 of that
// document is unchanged: no frame this path produces has ever been compared
// against a real GameCube frame, and the ceiling stays "framebuffer-
// equivalent, never pixel-identical".
// =============================================================================
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

const wasmPath = process.argv[2];
if (!wasmPath) {
  console.error("usage: node tools/gx_wgpipe_e2e_proof.mjs <assembly.wasm>");
  process.exit(2);
}

// Find the product repo (GotYaForce) by walking up from this script.
const here = path.dirname(fileURLToPath(import.meta.url));
let productRoot = null;
for (let dir = here; ; dir = path.dirname(dir)) {
  if (fs.existsSync(path.join(dir, "packages", "rom-runtime", "src", "gx", "fifo.ts"))) {
    productRoot = dir;
    break;
  }
  if (path.dirname(dir) === dir) break;
}
if (!productRoot) {
  console.log("SKIP packages/rom-runtime not present above this checkout");
  process.exit(3);
}

let esbuildEntry = null;
const pkgRequire = createRequire(
  pathToFileURL(path.join(productRoot, "packages", "rom-runtime", "package.json")).href,
);
try {
  esbuildEntry = pkgRequire.resolve("esbuild");
} catch {
  // pnpm store layout: a devDependency link is not always materialized.
  const store = path.join(productRoot, "node_modules", ".pnpm");
  if (fs.existsSync(store)) {
    const dir = fs.readdirSync(store).find((name) => name.startsWith("esbuild@"));
    if (dir) {
      const candidate = path.join(store, dir, "node_modules", "esbuild", "lib", "main.js");
      if (fs.existsSync(candidate)) esbuildEntry = candidate;
    }
  }
}
if (!esbuildEntry) {
  console.log("SKIP esbuild not installed in the product repo");
  process.exit(3);
}

const workDir = path.dirname(path.resolve(wasmPath));
const gxDir = path.join(productRoot, "packages", "rom-runtime", "src", "gx");
const rel = (file) => path.relative(workDir, path.join(gxDir, file)).split(path.sep).join("/");
const entryPath = path.join(workDir, "gx-host-entry.ts");
fs.writeFileSync(
  entryPath,
  "// Generated by tools/gx_wgpipe_e2e_proof.mjs. Re-exports the REAL host\n" +
    "// decode side so this proof cannot accidentally test a copy of it.\n" +
    `export { GxState } from "${rel("state.js")}";\n` +
    `export { GxFifo } from "${rel("fifo.js")}";\n` +
    `export { GxRecordingBackend } from "${rel("backend.js")}";\n` +
    `export { primitiveName } from "${rel("enums.js")}";\n`,
  "utf8",
);

const esbuild = await import(pathToFileURL(esbuildEntry).href);
const bundlePath = path.join(workDir, "gx-host-bundle.mjs");
await esbuild.build({
  entryPoints: [entryPath],
  outfile: bundlePath,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "es2022",
  logLevel: "silent",
});
const { GxState, GxFifo, GxRecordingBackend, primitiveName } = await import(
  pathToFileURL(bundlePath).href
);

const state = new GxState();
const backend = new GxRecordingBackend();
const fifo = new GxFifo(state, backend, null);

const mod = new WebAssembly.Module(fs.readFileSync(wasmPath));

// The ROM's GX entry points, wired to the host's own state object. This is
// the same translation packages/rom-runtime/src/gx/adapters.ts performs; the
// adapters marshal through the H2 bridged-call frame, which is the browser's
// transport and not what this proof is about.
const gxLog = [];
const entry = {
  gnt4_GXClearVtxDesc_bl: () => state.clearVtxDesc(),
  gnt4_GXSetVtxDesc_bl: (attr, type) => state.setVtxDesc(attr, type),
  gnt4_GXSetVtxAttrFmt_bl: (fmt, attr, cnt, type, frac) =>
    state.setVtxAttrFmt(fmt, attr, cnt, type, frac),
  gnt4_GXBegin_bl: (prim, fmt, n) => fifo.begin(prim, fmt, n),
};
const wg = {
  __gf_gx_wgpipe_u8: (v) => fifo.writeU8(v >>> 0),
  __gf_gx_wgpipe_u16: (v) => fifo.writeU16(v >>> 0),
  __gf_gx_wgpipe_u32: (v) => fifo.writeU32(v >>> 0),
  __gf_gx_wgpipe_f32: (v) => fifo.writeF32(v),
};

const imports = {};
const importedNames = [];
for (const imp of WebAssembly.Module.imports(mod)) {
  imports[imp.module] = imports[imp.module] || {};
  importedNames.push(imp.name);
  if (imp.kind !== "function") {
    if (imp.kind === "memory") imports[imp.module][imp.name] = new WebAssembly.Memory({ initial: 1 });
    else if (imp.kind === "global") imports[imp.module][imp.name] = 0;
    else if (imp.kind === "table")
      imports[imp.module][imp.name] = new WebAssembly.Table({ element: "anyfunc", initial: 1 });
    continue;
  }
  const fn = wg[imp.name] || entry[imp.name];
  imports[imp.module][imp.name] = (...args) => {
    gxLog.push(imp.name);
    return fn ? fn(...args) ?? 0 : 0;
  };
}

const instance = new WebAssembly.Instance(mod, imports);
const view = new DataView(instance.exports.memory.buffer);

// The arena state the ROM function's own guard reads before it draws.
const STRUCT = 0x80500000;
const COLOUR_SLOT = 0x80510000;
const RGBA = 0x8090a0b0; // r=0x80 g=0x90 b=0xa0 a=0xb0
view.setUint32(0x80433930, STRUCT, true);
view.setUint32(STRUCT + 0x38, 0, true);
view.setUint32(0x80436108, 1, true);
view.setUint32(0x8043610c, COLOUR_SLOT, true);
view.setUint32(COLOUR_SLOT, RGBA, true);

instance.exports.zz_0027c34_();

const checks = [];
const check = (name, actual, expected) => {
  checks.push({ name, ok: JSON.stringify(actual) === JSON.stringify(expected), actual, expected });
};

check(
  "the lowered module imports the host's write-gather symbols",
  ["__gf_gx_wgpipe_u8", "__gf_gx_wgpipe_u16", "__gf_gx_wgpipe_u32", "__gf_gx_wgpipe_f32"].filter(
    (n) => importedNames.includes(n),
  ),
  ["__gf_gx_wgpipe_u16", "__gf_gx_wgpipe_u32"],
);
check("the ROM function ran to completion without trapping", true, true);
check("primitives assembled by the host FIFO", fifo.primitiveCount, 1);
check("FIFO bytes dropped", fifo.droppedBytes, 0);
check("FIFO bytes left buffered", fifo.pendingBytes, 0);
check("the FIFO closed its primitive", fifo.inPrimitive, false);

const prim = backend.primitives[0];
check("a primitive reached the backend", Boolean(prim), true);
if (prim) {
  check("primitive byte and name", [prim.primitive, primitiveName(prim.primitive)], [0x80, "QUADS"]);
  check("vertex count", prim.vertexCount, 4);
  check("vertex format slot", prim.vtxfmt, 0);
  check(
    "positions decoded from the ROM's S16 XY stream",
    Array.from(prim.positions),
    [0, 0, 0, 640, 0, 0, 640, 448, 0, 0, 448, 0],
  );
  check(
    "colours decoded from the ROM's RGBA8 stream",
    Array.from(prim.colors),
    [0x80, 0x90, 0xa0, 0xb0, 0x80, 0x90, 0xa0, 0xb0, 0x80, 0x90, 0xa0, 0xb0, 0x80, 0x90, 0xa0, 0xb0],
  );
  check("the draw carried no normals and no texcoords", [prim.normals, prim.texcoords], [null, null]);
}
check(
  "the ROM's own GX setup crossed the seam, GXBegin immediately before the vertices",
  [gxLog[0], gxLog[gxLog.length - 13]],
  ["gnt4_GXSetCullMode_bl", "gnt4_GXBegin_bl"],
);
check("decode-side approximation diagnostics", backend.diagnostics.length, 0);

const failed = checks.filter((c) => !c.ok);
for (const c of checks) {
  console.log(
    `${c.ok ? "PASS" : "FAIL"}  ${c.name}` +
      (c.ok ? "" : `\n      actual  ${JSON.stringify(c.actual)}\n      expect  ${JSON.stringify(c.expected)}`),
  );
}
console.log("");
console.log(
  "GX_WGPIPE_E2E " +
    JSON.stringify({
      checks: checks.length,
      failed: failed.length,
      primitives: fifo.primitiveCount,
      droppedFifoBytes: fifo.droppedBytes,
      // Seam only. No frame produced by this path has ever been compared
      // against a real GameCube frame (docs/gx-hle-host.md section 1).
      verified: false,
    }),
);
process.exit(failed.length === 0 ? 0 : 1);
