"""Gate-emitted indirect-call lowering (design G2/H3, the OUTBOUND half).

Why this file exists
--------------------
`src/port_dispatch_companion.py` emits the address-keyed table, one adapter
thunk per function DEFINED in the window, the `__gf_dispatch` lookup entry
point and the `__gf_dispatch_miss` host import. That is the INBOUND half of
the uniform dispatch ABI: it lets something OUTSIDE the module call a ROM
function by its GameCube address.

It does nothing at all for the OUTBOUND direction, and the outbound direction
is where the ROM actually lives. The decompiled C is full of

    (*(code *)(&PTR_FUN_802d65b0)[*(char *)(param_1 + 0x580)])();
    (**(code **)(*piVar2 + 0x30))(piVar2);

-- 2307 such call sites across the 80-chunk export. `emcc` lowers each of them
to a `call_indirect` on the MODULE'S OWN function table, indexed by a value the
ROM computed as a GameCube CODE ADDRESS (0x80xxxxxx). That is wrong twice over:

  1. it traps or calls an arbitrary wrong function, because 0x80xxxxxx is not a
     wasm table index; and
  2. it is INVISIBLE. No import shim can observe a `call_indirect`, which is
     exactly why `research/tools/dolphin-trace/capture_transcript.py` REFUSES
     every function containing one (1602 functions, 14.6 % of the corpus, the
     single largest unverifiable class -- docs/verification-status.md section 3).

This module is the missing rewrite. It turns each such call site into a frame
build plus a call to `__gf_dispatch_at`, the companion's site-tagged entry to
the SAME address-keyed table. After lowering:

  * the call goes through a thunk the gate wrote, so it reaches the right ROM
    function or the declared miss import -- never a wasm table index;
  * and the call is OBSERVABLE, because the companion's trace mode declares
    `__gf_dispatch_enter` / `__gf_dispatch_exit` imports that see the site, the
    resolved GameCube target, the argument frame and the return.

Fail-closed, like `src/port_wgpipe_lowering.py`
-----------------------------------------------
Every `(*(code *)` / `(**(code **)` occurrence in the window's derived sources
must be either LOWERED or explained. A surviving one is a wrong-function call
at run time, which is worse than a refused window, so anything this pass cannot
confidently rewrite becomes a loud `indirect_lowering_failed` refusal:

  `indirect_unparsed`      the cast is there but the call shape did not parse
  `indirect_value_context` the call's RESULT IS USED. Refused deliberately: the
                           frame's i32 result is only a VIEW of the return slot
                           (the frame header states the asymmetry -- for an i64
                           return it is NOT the PPC r3 image), and an indirect
                           site has no callee prototype from which to derive the
                           true return class. Silently narrowing a return is
                           precisely the "signature traps become silent
                           mis-marshalling" risk the design records as C8.

Non-call uses of the cast (`if (*(code **)(x + 0x100) != (code *)0x0)`) are
NOT call sites and are left exactly as they are; they are counted so the
evidence can show they were seen and classified rather than missed.

The rewrite is GATE-OWNED, like the write-gather-pipe lowering: it edits the
derived window sources in the gate workdir. The verbatim `unit.c` in
`research/decomp/port-units-staging/` is never touched.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from typing import Any

HEADER_FILENAME = "gf_indirect_lowering.h"
SITES_FILENAME = "gf_indirect_sites.json"

# The companion's site-tagged dispatch entry (src/port_dispatch_companion.py).
DISPATCH_AT = "__gf_dispatch_at"

# Frame capacity, mirrored from the frame ABI header. A call site with more
# arguments than this cannot be marshalled and is a refusal, never a truncation.
MAX_ARGS = 16

# Value classes recorded per argument slot at RUN TIME by the emitted
# `_Generic` selection. They mirror GF_DISPATCH_CLASS_* in the frame header.
CLASS_VOID, CLASS_I32, CLASS_I64, CLASS_F32, CLASS_F64 = 0, 1, 2, 3, 4

HEADER_TEXT = """/* gf_indirect_lowering.h -- GF outbound indirect-call lowering, version 1.
 *
 * AUTO-GENERATED by the assembly gate (src/port_indirect_lowering.py).
 * DERIVED artifact: never hand-edited, regenerated on every window link.
 *
 * The ROM's `(*(code *)addr)(args)` becomes, textually:
 *
 *   do {
 *     __gf_indirect_call __gf_c;
 *     __gf_indirect_begin(&__gf_c);
 *     __GF_ARG(__gf_c, 0, <arg0>);
 *     __GF_ARG(__gf_c, 1, <arg1>);
 *     __gf_c.frame.arg_count = 2u;
 *     __gf_dispatch_at(<site>, (unsigned int)(<target>),
 *                      __GF_ADDR(&__gf_c.frame), __GF_ADDR(__gf_c.classes));
 *   } while (0);
 *
 * WHY A PER-CALL LOCAL FRAME. The frame lives on the C stack, so it is at a
 * real linear-memory address, it is reentrancy- and recursion-safe, and it
 * costs no allocator. Its address is what the uniform ABI calls `argptr`.
 *
 * WHY `_Generic`. The frame's slots are class-tagged (i32/i64/f32/f64) and a
 * decompiled call site gives no prototype for its callee, so the ONLY
 * authority for an argument's class is the STATIC TYPE OF THE ARGUMENT
 * EXPRESSION ITSELF. `_Generic` reads exactly that, at compile time, from the
 * expression the ROM's own C hands the call. Nothing is guessed and nothing is
 * hand-listed. The class is ALSO written into a parallel `classes` array so
 * the host observing the dispatch can read each slot at the width the module
 * wrote it -- the observer never has to assume a signature.
 *
 * Sub-i32 integers reach the slot CALLER-EXTENDED, which is the frame ABI's
 * stated argument convention: the usual arithmetic conversions promote a
 * `char`/`short`/`unsigned char` argument to `int`/`unsigned int` at the call,
 * and `__gf_arg_w` stores that already-extended 32-bit value.
 *
 * Pointers take the `default` branch and convert to `unsigned int`. That is
 * the design's pointer marshalling (a 32-bit linear-memory address) and it
 * relies on `-Wno-int-conversion`, which the unit and window builds both pass.
 */
#ifndef GF_INDIRECT_LOWERING_H
#define GF_INDIRECT_LOWERING_H

#include "gf_dispatch_frame.h"

#define GF_INDIRECT_LOWERING_VERSION 1

/* The companion's site-tagged dispatch entry. `classptr` is the address of the
 * per-call class array; the companion passes both straight through to the
 * observation imports in trace mode and ignores them otherwise. */
extern int __gf_dispatch_at(unsigned int site, unsigned int gc_addr, int argptr,
                            int classptr);

typedef struct __gf_indirect_call {
  __gf_dispatch_frame frame;
  unsigned char classes[GF_DISPATCH_MAX_ARGS];
} __gf_indirect_call;

static void __gf_indirect_begin(__gf_indirect_call *c) {
  unsigned int i = 0u;
  c->frame.arg_count = 0u;
  c->frame.ret_class = GF_DISPATCH_CLASS_VOID;
  c->frame.ret.i64 = 0;
  for (i = 0u; i < (unsigned int)GF_DISPATCH_MAX_ARGS; ++i) {
    c->frame.args[i].i64 = 0;
    c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_VOID;
  }
}

/* One setter per wasm value class. `_Generic` selects the FUNCTION, and the
 * call is type-checked only against the selected one -- the unselected
 * associations are function designators and are always well formed. */
static void __gf_arg_w(__gf_indirect_call *c, unsigned int i, unsigned int v) {
  c->frame.args[i].i64 = 0;
  c->frame.args[i].u32 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I32;
}
static void __gf_arg_i64(__gf_indirect_call *c, unsigned int i, long long v) {
  c->frame.args[i].i64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I64;
}
static void __gf_arg_u64(__gf_indirect_call *c, unsigned int i,
                         unsigned long long v) {
  c->frame.args[i].u64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I64;
}
static void __gf_arg_f32(__gf_indirect_call *c, unsigned int i, float v) {
  c->frame.args[i].i64 = 0;
  c->frame.args[i].f32 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_F32;
}
static void __gf_arg_f64(__gf_indirect_call *c, unsigned int i, double v) {
  c->frame.args[i].f64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_F64;
}

#define __GF_ARG(c, i, v)                                                     \\
  _Generic((v),                                                               \\
           float: __gf_arg_f32,                                               \\
           double: __gf_arg_f64,                                              \\
           long long: __gf_arg_i64,                                           \\
           unsigned long long: __gf_arg_u64,                                  \\
           default: __gf_arg_w)(&(c), (unsigned int)(i), (v))

/* A linear-memory address as the uniform ABI's i32. */
#define __GF_ADDR(p) ((int)(unsigned int)(unsigned long)(p))

/* Read the pointer a `(**(code **)E)(...)` site dereferences. E is a GC
 * address in linear memory holding the callee's code address. */
#define __GF_DEREF(e) (*(unsigned int *)(unsigned int)(e))

#endif /* GF_INDIRECT_LOWERING_H */
"""


@dataclass(frozen=True)
class IndirectProblem:
    """One reason the lowering cannot proceed. The gate refuses on any."""

    unit: str
    source: str
    code: str
    detail: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "unit": self.unit,
            "source": self.source,
            "code": self.code,
            "detail": self.detail,
        }


@dataclass(frozen=True)
class IndirectSite:
    """One lowered call site, as the evidence records it."""

    unit: str
    source: str
    function: str
    site: str  # 8 lowercase hex digits: the site's GC address, or a synthetic id
    site_kind: str  # "gc_address" | "ordinal"
    shape: str  # "code_ptr" | "code_ptr_ptr"
    arg_count: int
    target_expr: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "unit": self.unit,
            "source": self.source,
            "function": self.function,
            "site": self.site,
            "site_kind": self.site_kind,
            "shape": self.shape,
            "arg_count": self.arg_count,
            "target_expr": self.target_expr,
        }


@dataclass
class IndirectResult:
    sources: dict[str, str] = field(default_factory=dict)
    sites: list[IndirectSite] = field(default_factory=list)
    problems: list[IndirectProblem] = field(default_factory=list)
    non_call_casts: int = 0


# `// ==== 80079a40  FUN_80079a40 ====` -- the verbatim extraction format's
# per-definition address record. Same regex the companion and the owner
# registry use; it is what binds a lowered site to a ROM function.
_MARKER_RE = re.compile(
    r"//\s*====\s*([0-9A-Fa-f]{8})\s+([A-Za-z_][A-Za-z0-9_]*)\s*===="
)

# The two call shapes Ghidra emits for a `bctrl`. Measured over the 80-chunk
# export: 1555 `(*(code *)`, 752 `(**(code **)`, plus 100 `(*(code **)` that
# are NOT calls (`if (*(code **)(x + 0x100) != (code *)0x0)`).
_CAST_RE = re.compile(r"\(\s*(\*+)\s*\(\s*code\s*(\*+)\s*\)")

_MASKED_RE = re.compile(
    r"/\*.*?\*/|//[^\n]*|\"(?:\\.|[^\"\\\n])*\"|'(?:\\.|[^'\\\n])*'", re.S
)


def _mask_comments_and_strings(text: str) -> str:
    """Replace comments/string literals with spaces, preserving offsets."""

    def blank(match: re.Match[str]) -> str:
        return "".join("\n" if ch == "\n" else " " for ch in match.group(0))

    return _MASKED_RE.sub(blank, text)


def _match_paren(masked: str, opening: int) -> int | None:
    """Index of the `)` matching the `(` at `opening`, or None."""
    depth = 0
    for index in range(opening, len(masked)):
        ch = masked[index]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return index
    return None


def _skip_space(masked: str, index: int) -> int:
    while index < len(masked) and masked[index] in " \t\r\n":
        index += 1
    return index


def _split_args(text: str) -> list[str] | None:
    """Split a call's argument text on TOP-LEVEL commas.

    Returns [] for an empty list. None if the text is unbalanced, which the
    caller turns into an `indirect_unparsed` refusal rather than a guess.
    """
    if not text.strip():
        return []
    out: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
            if depth < 0:
                return None
        if ch == "," and depth == 0:
            out.append("".join(current))
            current = []
            continue
        current.append(ch)
    if depth != 0:
        return None
    out.append("".join(current))
    return [item.strip() for item in out]


def _statement_context(masked: str, start: int) -> bool:
    """True when the call at `start` is a whole statement, not a value.

    Scans back over whitespace to the previous significant character. A call
    that begins a statement is preceded by `;`, `{`, `}`, `:` (a label), or the
    `)` that closes an `if (...)`/`else`/`while (...)` head, or nothing at all.
    Anything else -- `=`, `,`, an operator, `(` -- means the RESULT IS USED,
    which this pass refuses rather than mis-marshals.
    """
    index = start - 1
    while index >= 0 and masked[index] in " \t\r\n":
        index -= 1
    if index < 0:
        return True
    ch = masked[index]
    if ch in ";{}":
        return True
    if ch == ":":
        # A `:` is a statement position ONLY when it closes a LABEL
        # (`LAB_80010e2c:`, `default:`, `case 3:`). It is NOT one when it
        # separates the arms of a conditional operator, and there the RESULT
        # IS USED: `x = c ? 0 : (*(code *)p[3])(p);` must be refused exactly as
        # `x = (*(code *)p[3])(p);` is. Treating every `:` as a label was a
        # FAIL-OPEN hole in a fail-closed pass -- it would have narrowed those
        # returns through the frame's i32 view (design C8) without a word.
        return _closes_a_label(masked, index)
    if ch != ")":
        return False
    # `) (*(code *)...` -- only a control-flow head may precede a statement.
    opening = _open_paren_of(masked, index)
    if opening is None:
        return False
    index = opening - 1
    while index >= 0 and masked[index] in " \t\r\n":
        index -= 1
    word_end = index + 1
    while index >= 0 and (masked[index].isalnum() or masked[index] == "_"):
        index -= 1
    keyword = masked[index + 1 : word_end]
    return keyword in {"if", "while", "for", "else"}


def _word_before(masked: str, index: int) -> tuple[str, int]:
    """The identifier/number ending at or before `index`, and where it starts.

    Returns ("", index) when the preceding token is not a word.
    """
    while index >= 0 and masked[index] in " \t\r\n":
        index -= 1
    end = index + 1
    while index >= 0 and (masked[index].isalnum() or masked[index] == "_"):
        index -= 1
    return masked[index + 1 : end], index


def _closes_a_label(masked: str, colon: int) -> bool:
    """True when the `:` at `colon` terminates a statement LABEL.

    The three shapes the decompiled corpus emits, and nothing else:

        LAB_80010e2c:          an identifier, itself at statement position
        default:               likewise
        case 3:                a constant, preceded by the `case` keyword

    A conditional operator's `:` fails all three -- the token before it is an
    expression whose own predecessor is an operator, `(` or `,`, never `;`,
    `{`, `}` or another label. Anything this cannot recognise is reported as
    NOT a label, which sends the call site to the value-context refusal: the
    safe direction, since a refusal costs a window and a false statement
    position costs a silently narrowed return.
    """
    word, before = _word_before(masked, colon - 1)
    if not word:
        return False
    if word.isdigit() or (word.startswith("0x") and len(word) > 2):
        # `case 3:` / `case 0x10:` -- the constant's predecessor must be `case`
        keyword, before = _word_before(masked, before)
        if keyword != "case":
            return False
    while before >= 0 and masked[before] in " \t\r\n":
        before -= 1
    return before < 0 or masked[before] in ";{}:"


def _open_paren_of(masked: str, closing: int) -> int | None:
    depth = 0
    for index in range(closing, -1, -1):
        ch = masked[index]
        if ch == ")":
            depth += 1
        elif ch == "(":
            depth -= 1
            if depth == 0:
                return index
    return None


def _enclosing_function(markers: list[tuple[int, str, str]], offset: int) -> tuple[str, str]:
    """(gc_address, symbol) of the marker preceding `offset`."""
    best = ("", "")
    for position, address, symbol in markers:
        if position <= offset:
            best = (address.lower(), symbol)
        else:
            break
    return best


def _markers(masked: str, text: str) -> list[tuple[int, str, str]]:
    out = []
    for match in _MARKER_RE.finditer(text):
        out.append((match.start(), match.group(1), match.group(2)))
    out.sort()
    del masked
    return out


def lower_source(unit: str, source_name: str, text: str,
                 site_seed: int = 0) -> tuple[str, list[IndirectSite],
                                              list[IndirectProblem], int, int]:
    """Rewrite every indirect CALL in one translation unit.

    Returns (new_text, sites, problems, non_call_casts, next_site_seed).

    Sites are identified by the GC ADDRESS OF THE ENCLOSING FUNCTION plus an
    ordinal within it, because the decompiled C carries no per-instruction
    address. The identifier is stable for a given source text, which is what a
    capture plan and a replay both need in order to name the same site.
    """
    masked = _mask_comments_and_strings(text)
    markers = _markers(masked, text)
    sites: list[IndirectSite] = []
    problems: list[IndirectProblem] = []
    non_call = 0
    edits: list[tuple[int, int, str]] = []
    per_function: dict[str, int] = {}

    for match in _CAST_RE.finditer(masked):
        outer_open = match.start()
        stars_call, stars_type = match.group(1), match.group(2)
        closing = _match_paren(masked, outer_open)
        if closing is None:
            problems.append(IndirectProblem(
                unit, source_name, "indirect_unparsed",
                f"unbalanced parentheses after `{match.group(0).strip()}` at offset {outer_open}"))
            continue
        after = _skip_space(masked, closing + 1)
        if after >= len(masked) or masked[after] != "(":
            # `if (*(code **)(x + 0x100) != (code *)0x0)` -- a comparison, a
            # null test or an assignment of the pointer, not a call. Counted so
            # the evidence shows it was classified, never silently skipped.
            non_call += 1
            continue
        args_close = _match_paren(masked, after)
        if args_close is None:
            problems.append(IndirectProblem(
                unit, source_name, "indirect_unparsed",
                f"unbalanced argument list at offset {after}"))
            continue

        # shape: `(*(code *)E)` derefs once through a `code *`;
        #        `(**(code **)E)` derefs the pointer stored AT E.
        depth = len(stars_call)
        if depth != len(stars_type) or depth not in (1, 2):
            problems.append(IndirectProblem(
                unit, source_name, "indirect_unparsed",
                f"unrecognised indirection depth `{match.group(0).strip()}` at offset {outer_open}"))
            continue
        shape = "code_ptr" if depth == 1 else "code_ptr_ptr"

        target_expr = text[match.end():closing].strip()
        if not target_expr:
            problems.append(IndirectProblem(
                unit, source_name, "indirect_unparsed",
                f"empty call-target expression at offset {outer_open}"))
            continue

        args = _split_args(text[after + 1:args_close])
        if args is None:
            problems.append(IndirectProblem(
                unit, source_name, "indirect_unparsed",
                f"unparsable argument list at offset {after}"))
            continue
        if len(args) > MAX_ARGS:
            problems.append(IndirectProblem(
                unit, source_name, "indirect_arity_overflow",
                f"{len(args)} arguments exceeds the frame's {MAX_ARGS} slots at offset {outer_open}"))
            continue

        address, symbol = _enclosing_function(markers, outer_open)
        if not _statement_context(masked, outer_open):
            problems.append(IndirectProblem(
                unit, source_name, "indirect_value_context",
                f"the result of the indirect call in {symbol or source_name} at offset "
                f"{outer_open} IS USED. The uniform frame's i32 result is only a VIEW of "
                f"the return slot and an indirect site has no callee prototype to derive "
                f"the true return class from, so lowering it would narrow the return "
                f"silently (design C8). Refused."))
            continue

        if address:
            ordinal = per_function.get(address, 0)
            per_function[address] = ordinal + 1
            site_id = f"{address}:{ordinal}"
            site_kind = "gc_address"
        else:
            site_id = f"ord{site_seed:04d}"
            site_seed += 1
            site_kind = "ordinal"

        edits.append((outer_open, args_close + 1,
                      _emit_call(site_id, shape, target_expr, args)))
        sites.append(IndirectSite(
            unit=unit, source=source_name, function=symbol or "",
            site=site_id, site_kind=site_kind, shape=shape,
            arg_count=len(args), target_expr=target_expr))

    if problems:
        return text, sites, problems, non_call, site_seed

    out = text
    for start, stop, replacement in sorted(edits, reverse=True):
        out = out[:start] + replacement + out[stop:]
    if edits and "gf_indirect_lowering.h" not in out:
        out = f'#include "{HEADER_FILENAME}"\n' + out
    return out, sites, problems, non_call, site_seed


def site_word(site_id: str) -> int:
    """The 32-bit wire form of a site id.

    `<8-hex gc addr>:<ordinal>` packs the address's low 28 bits (the leading
    `0x8` nibble of a MEM1 code address is implied) with the per-function
    ordinal in the top 4 bits. `decode_site_token` is the exact inverse, and
    both the capture plan and the replay artifact carry the full string form
    as well, so nothing depends on the packing being readable.
    """
    if ":" in site_id:
        address, ordinal = site_id.split(":", 1)
        return ((int(address, 16) & 0x0FFFFFFF) | ((int(ordinal) & 0xF) << 28))
    digest = hashlib.sha256(site_id.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") & 0x0FFFFFFF


def _emit_call(site_id: str, shape: str, target_expr: str,
               args: list[str]) -> str:
    """The lowered statement for one call site.

    A single `do { ... } while (0)` so it remains ONE statement: several of
    these sites are the unbraced body of an `if`, and a bare block would change
    the program's control flow.
    """
    site_c = f"0x{site_word(site_id):08x}u"
    target = f"(unsigned int)({target_expr})" if shape == "code_ptr" \
        else f"__GF_DEREF({target_expr})"
    parts = [
        "do { __gf_indirect_call __gf_c; __gf_indirect_begin(&__gf_c); ",
    ]
    for index, arg in enumerate(args):
        parts.append(f"__GF_ARG(__gf_c, {index}u, ({arg})); ")
    parts.append(f"__gf_c.frame.arg_count = {len(args)}u; ")
    parts.append(
        f"{DISPATCH_AT}({site_c}, {target}, "
        f"__GF_ADDR(&__gf_c.frame), __GF_ADDR(__gf_c.classes)); "
    )
    parts.append("} while (0)")
    return "".join(parts)


def decode_site_token(token: int) -> str:
    """Inverse of the `site` word the emitted C passes to `__gf_dispatch_at`.

    The wire form packs the enclosing function's GC address (low 28 bits, the
    0x8 nibble is implied) and the per-function ordinal (top 4 bits) into one
    i32, so a trace line is self-describing.
    """
    ordinal = (token >> 28) & 0xF
    address = 0x80000000 | (token & 0x0FFFFFFF)
    return f"{address:08x}:{ordinal}"


def lower_window(sources: list[tuple[str, str, str]]) -> IndirectResult:
    """Lower every source in a window. `sources` is [(unit, name, text)]."""
    result = IndirectResult()
    seed = 0
    for unit, name, text in sources:
        new_text, sites, problems, non_call, seed = lower_source(unit, name, text, seed)
        result.problems.extend(problems)
        result.sites.extend(sites)
        result.non_call_casts += non_call
        if not problems:
            result.sources[name] = new_text
    if result.problems:
        result.sources = {}
    return result


def lowering_evidence(result: IndirectResult) -> dict[str, Any]:
    """The gate-result evidence block for one lowered window."""
    by_shape: dict[str, int] = {}
    for site in result.sites:
        by_shape[site.shape] = by_shape.get(site.shape, 0) + 1
    payload = {
        "version": 1,
        "header": HEADER_FILENAME,
        "sites_manifest": SITES_FILENAME,
        "dispatch_entry": DISPATCH_AT,
        "sites": len(result.sites),
        "sites_by_shape": by_shape,
        "non_call_casts": result.non_call_casts,
        "functions": sorted({site.function for site in result.sites if site.function}),
        "table": [site.to_dict() for site in result.sites],
    }
    payload["manifest_sha256"] = hashlib.sha256(
        json.dumps(payload["table"], sort_keys=True).encode("utf-8")
    ).hexdigest()
    return payload


def sites_manifest(result: IndirectResult) -> str:
    """The committed site manifest a capture plan and a replay both read."""
    return json.dumps(
        {
            "indirect_sites_schema": 1,
            "generated_by": "src/port_indirect_lowering.py",
            "dispatch_entry": DISPATCH_AT,
            "sites": [site.to_dict() for site in result.sites],
        },
        indent=1,
    ) + "\n"


def header_problems(text: str) -> list[str]:
    """Sanity checks on the emitted header, so a drift is loud."""
    problems = []
    for needed in ("__gf_indirect_call", "__GF_ARG", "__GF_ADDR", DISPATCH_AT):
        if needed not in text:
            problems.append(f"emitted header lost `{needed}`")
    return problems
