"""D5 acceptance-gate item 3: the pilot probe (docs/d5-idiom-fix-design.md D5-7.3).

Rebuilds auto-c0035-002's unit.c THROUGH the D5 fp-reinterpret transform
(read-only from the export; all outputs go to a caller-supplied scratch
directory), compiles it with the driver's own emcc invocation
(``emcc_build_unit`` -- the identical production build path), and probes
``FUN_80131688`` with s16 inputs {100, 50, -200, 0} at ``param_9+0x1900``.

Pass criterion (gate 3): the four stored values are distinct,
input-proportional, equal to the PPC-semantics reference
``(short)(int)((double)(float)(double)x * FLOAT_80439e80_value)`` computed at
runtime from the same arena value (fctiwz truncates toward zero) -- and
specifically not the pre-fix saturation artifact -1.

Arena values written by the probe are the ROM values the unit's oracle spec
records (research/decomp/oracle-harness/specs/auto-c0035-002.spec.mjs):
FLOAT_80439e80 = 0.96f (wrapper timer scale), DOUBLE_80439e88 = 2^52 + 2^31
(int->double magic), FLOAT_80439e90 = -1.0 (stream arm rate).

Run:  .venv\\Scripts\\python.exe -m src.port_d5_probe [--repo D:\\GotYaForce]
      [--workdir <scratch>] [--json]

The migration step runs this as its gate-3 check; the offline test suite
runs it too when the emsdk + node toolchain is present (skips otherwise).
"""

from __future__ import annotations

import argparse
import json
import struct
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from src.port_fp_transform import ensure_bitcast_helper
from src.port_wasm_units import (
    NO_WINDOW,
    emcc_build_unit,
    materialize_unit_c,
    resolve_node_exe,
)

PROBE_UNIT = "auto-c0035-002"
PROBE_FUNCTION = "FUN_80131688"
PROBE_INPUTS = [100, 50, -200, 0]
ACT = 0x80600000  # scratch actor base, free region above all DOL/bss sections

_HARNESS = """\
// D5 gate-3 probe harness (generated by src/port_d5_probe.py; scratch-only).
import fs from "node:fs";
const wasmBytes = fs.readFileSync(process.argv[2]);
const module = await WebAssembly.compile(wasmBytes);
const stub = () => 0;
const instance = await WebAssembly.instantiate(module, {
  env: new Proxy({}, { get: () => stub }),
});
const ex = instance.exports;
const dv = new DataView(ex.memory.buffer);
const fr = (x) => Math.fround(x);
// ROM arena values (spec-recorded): timer scale, int->double magic, arm rate.
dv.setFloat32(0x80439e80, 0.96, true);
dv.setFloat64(0x80439e88, 4503599627370496 + 2147483648, true);
dv.setFloat32(0x80439e90, -1.0, true);
const ACT = %(act)d;
const scale = dv.getFloat32(0x80439e80, true); // f32 witness of the arena value
const results = [];
for (const input of %(inputs)s) {
  // reset the actor region the unit writes so cases are independent
  new Uint8Array(ex.memory.buffer, ACT, 0x1e00).fill(0);
  dv.setInt16(ACT + 0x1900, input, true);
  ex.%(fn)s(0n, 0n, 0, 0, 0, 0, 0, 0, ACT, 0, 0, 0, 0, 0, 0, 0);
  const stored = dv.getInt16(ACT + 0x1900, true);
  // PPC reference: fctiwz truncates toward zero; the float chain
  // (double)(float)(double)x is exact for these inputs.
  const reference = (Math.trunc(fr(input) * scale) << 16) >> 16;
  results.push({ input, stored, reference });
}
console.log(JSON.stringify({ scale, results }));
"""


def run_probe(
    repo_root: Path, workdir: Path | None = None
) -> dict[str, Any]:
    repo_root = Path(repo_root)
    queue_path = (
        repo_root / "research/decomp/generated/finish-game-port/wasm-units.json"
    )
    queue = json.loads(queue_path.read_text(encoding="utf-8-sig"))
    units = queue["units"] if isinstance(queue, dict) else queue
    unit = next(u for u in units if u["name"] == PROBE_UNIT)

    if workdir is None:
        workdir = Path(tempfile.mkdtemp(prefix="d5-probe-"))
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    materialized = materialize_unit_c(repo_root, unit)
    header = ensure_bitcast_helper(
        (repo_root / unit["header_seed"]).read_text(encoding="utf-8")
    )
    (workdir / "unit.c").write_text(
        materialized.unit_c, encoding="utf-8", newline="\n"
    )
    (workdir / "gnt4_shim.h").write_text(header, encoding="utf-8", newline="\n")

    linked, build_error = emcc_build_unit(
        repo_root,
        workdir,
        unit["exported_functions"],
        unit.get("allowed_extra_imports") or None,
    )
    if not linked:
        return {
            "ok": False,
            "stage": "build",
            "error": build_error[-2000:],
            "transform": materialized.transform,
            "workdir": str(workdir),
        }

    harness = _HARNESS % {
        "act": ACT,
        "inputs": json.dumps(PROBE_INPUTS),
        "fn": PROBE_FUNCTION,
    }
    harness_path = workdir / "d5-probe.mjs"
    harness_path.write_text(harness, encoding="utf-8", newline="\n")
    completed = subprocess.run(
        [resolve_node_exe(), str(harness_path), str(workdir / "unit.wasm")],
        capture_output=True,
        text=True,
        timeout=120,
        creationflags=NO_WINDOW,
    )
    if completed.returncode != 0:
        return {
            "ok": False,
            "stage": "probe",
            "error": (completed.stderr + completed.stdout)[-2000:],
            "transform": materialized.transform,
            "workdir": str(workdir),
        }
    probe = json.loads(completed.stdout.strip().splitlines()[-1])
    results = probe["results"]

    # Python-side independent reference (same PPC semantics, no shared code
    # with the harness): f32(0.96) widened to f64, multiply, trunc to zero.
    scale = struct.unpack("<f", struct.pack("<f", 0.96))[0]
    for row in results:
        row["reference_py"] = int(float(row["input"]) * scale)  # trunc to 0

    stored = [row["stored"] for row in results]
    checks = {
        "distinct": len(set(stored)) == len(stored),
        "not_saturated": all(value != -1 for value in stored),
        "input_proportional": all(
            (row["input"] > 0) == (row["stored"] > 0)
            and (row["input"] == 0) == (row["stored"] == 0)
            for row in results
        ),
        "matches_reference": all(
            row["stored"] == row["reference"] == row["reference_py"]
            for row in results
        ),
    }
    return {
        "ok": all(checks.values()),
        "stage": "done",
        "checks": checks,
        "results": results,
        "scale_f32": probe["scale"],
        "transform": materialized.transform,
        "workdir": str(workdir),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", default=r"D:\GotYaForce")
    parser.add_argument("--workdir", default=None)
    parser.add_argument("--json", action="store_true", dest="as_json")
    args = parser.parse_args(argv)
    report = run_probe(
        Path(args.repo), Path(args.workdir) if args.workdir else None
    )
    if args.as_json:
        print(json.dumps(report, indent=2))
    else:
        print(f"gate-3 probe {'PASS' if report['ok'] else 'FAIL'}")
        for key, value in report.items():
            if key != "results":
                print(f"  {key}: {value}")
        for row in report.get("results", []):
            print(
                f"  input {row['input']:>5} -> stored {row['stored']:>5} "
                f"(reference {row['reference']})"
            )
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
