"""Gate-emitted dispatch companion (design G2/H3: address-keyed uniform ABI).

The ROM is dispatch-table-driven: stored function pointers in game data are
GameCube 0x80xxxxxx CODE addresses sitting in the shared linear memory, and a
composed wasm module has no way to call them (docs/playable-port-design.md,
section V3 G2). The normative mechanism (V4 H3, upheld by the V5 verdict) is a
UNIFORM DISPATCH ABI: link-time adapter thunks with ONE canonical signature,
an address-keyed registration table, and a defined miss-handler import that
routes unknown addresses to the host bridge -- a miss is a bridge call, never
a trap and never undefined behavior.

This module is the derivation half of that mechanism. At window link time the
assembly gate (src/port_assembly_gate.py) asks it to:

  1. derive, for every function DEFINED in the window's units, the callee's
     GC address and marshalling signature (from the unit's own chunk markers
     and definition heads -- the authoritative in-artifact evidence -- with
     zz_/FUN_ name encoding and the owner registry as fallbacks);
  2. emit a companion C translation unit containing one adapter thunk per
     defined function (canonical signature `int __gf_thunk_<addr>(int)`), the
     address-keyed table, the `__gf_dispatch` lookup entry point, and the
     declared `__gf_dispatch_miss` import; plus the frame-ABI header the
     thunks marshal through.

Everything here is DERIVED, never hand-edited, and fails closed: a defined
function whose address or signature cannot be derived is a companion problem
the gate turns into a loud `dispatch_companion_failed` refusal -- never a
silent skip (a defined function silently routed to the miss handler would be
a wrong-behavior bridge call, not a defined miss).

Import-light on purpose: only src.port_assembly_abi, whose
`dispatch_value_class` / `symbol_gc_address` are the single-source machinery
for wasm value classes and name-encoded addresses.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from src.port_assembly_abi import dispatch_value_class, symbol_gc_address

FRAME_HEADER_FILENAME = "gf_dispatch_frame.h"
COMPANION_FILENAME = "gf_dispatch_companion.c"
DISPATCH_EXPORT = "__gf_dispatch"
MISS_IMPORT = "__gf_dispatch_miss"
# Arity ledger (design "flagged to the ledger"): a caller whose arg_count
# differs from the callee's known arity still dispatches (PPC indirect calls
# are signature-agnostic; the register-residue class is legitimate, V5 note
# 1) but the event is counted in a module global the host reads through this
# export. A counter costs one compare on the match path and no import
# plumbing; it can never turn a legitimate cross-class call into a failure.
ARITY_EXPORT = "__gf_dispatch_arity_mismatches"

# ---- the OUTBOUND half (src/port_indirect_lowering.py) --------------------
# `__gf_dispatch` is what something OUTSIDE the module calls to reach a ROM
# function by address. `__gf_dispatch_at` is what the ROM'S OWN lowered
# `bctrl` call sites call: the same table, plus the SITE the call came from.
# It is emitted ONLY when the indirect-call lowering is requested, so a
# companion built without the lowering is byte-identical to what it was.
DISPATCH_AT_EXPORT = "__gf_dispatch_at"
# Observation imports, emitted only in TRACE mode. They are what makes the
# 1602 ROM-function-pointer-dispatch functions observable at all: a
# `call_indirect` hides from an import shim, but a thunk the gate wrote does
# not have to. See research/decomp/oracle-harness/run-dispatch.mjs.
TRACE_ENTER_IMPORT = "__gf_dispatch_enter"
TRACE_EXIT_IMPORT = "__gf_dispatch_exit"

FRAME_ABI_VERSION = 1
FRAME_MAX_ARGS = 16

# Frame layout constants, mirrored in FRAME_HEADER_TEXT below and asserted
# there with _Static_assert. This is the seam trace verification will cross:
# keep the numbers in exactly two places (here and the header) and let the
# compiler prove the header's copy.
FRAME_SLOT_SIZE = 8
FRAME_RET_OFFSET = 0x08
FRAME_ARGS_OFFSET = 0x10
FRAME_SIZE = FRAME_ARGS_OFFSET + FRAME_MAX_ARGS * FRAME_SLOT_SIZE  # 0x90

CLASS_CODES = {"void": 0, "i32": 1, "i64": 2, "f32": 3, "f64": 4}
_CLASS_MACROS = {
    "void": "GF_DISPATCH_CLASS_VOID",
    "i32": "GF_DISPATCH_CLASS_I32",
    "i64": "GF_DISPATCH_CLASS_I64",
    "f32": "GF_DISPATCH_CLASS_F32",
    "f64": "GF_DISPATCH_CLASS_F64",
}
_CLASS_C_TYPES = {"i32": "int", "i64": "long long", "f32": "float", "f64": "double"}
_CLASS_SLOT_MEMBERS = {"i32": "i32", "i64": "i64", "f32": "f32", "f64": "f64"}

FRAME_HEADER_TEXT = """/* gf_dispatch_frame.h -- GF uniform dispatch frame ABI, version 1.
 *
 * AUTO-GENERATED by the assembly gate (src/port_dispatch_companion.py).
 * DERIVED artifact: never hand-edited, regenerated on every window link.
 *
 * Design contract (docs/playable-port-design.md V4 H3): every entry in the
 * address-keyed function table is an adapter thunk with ONE canonical wasm
 * signature, (i32 argptr) -> i32. `argptr` is the byte address, in the shared
 * linear memory, of one __gf_dispatch_frame. The thunk unmarshals the frame
 * into the callee's true parameters, calls the callee directly, and marshals
 * the return back into the frame.
 *
 * Frame layout (fixed, little-endian wasm32 linear memory):
 *
 *   offset 0x00  u32 arg_count   caller-written: how many arg slots the CALL
 *                                SITE populated. Informational/ledger data
 *                                only -- thunks never gate on it, because PPC
 *                                indirect calls are signature-agnostic and a
 *                                cross-class caller legitimately writes fewer
 *                                slots than the callee reads (the register-
 *                                residue class, V5 note 1).
 *   offset 0x04  u32 ret_class   thunk-written: GF_DISPATCH_CLASS_* of the
 *                                value in the return slot (VOID => slot 0).
 *   offset 0x08  slot ret        thunk-written return slot (8 bytes).
 *   offset 0x10  slot args[16]   caller-written argument slots, one 8-byte
 *                                slot per argument, in callee parameter
 *                                order. i32/f32 occupy the LOW 4 bytes of
 *                                their slot; i64/f64 occupy all 8.
 *
 *   sizeof(frame) == 0x90, alignment 8.
 *
 * Return convention: the thunk's i32 result is the i32 VIEW of the return
 * value (the value itself for i32 returns, the LOW 32 bits for i64, 0 for
 * f32/f64/void). NOTE the deliberate asymmetry with the source ABI: PPC32
 * EABI returns an i64 in r3:r4 with r3 carrying the HIGH word, so for i64
 * returns the thunk's i32 result is NOT an r3 image. Consumers MUST read
 * the full 8-byte ret slot (+0x08) for i64/f32/f64 returns; the frame's
 * ret slot + ret_class are the authoritative, full-width return channel,
 * and the i32 result is a convenience view only.
 *
 * Argument convention: sub-i32 integer arguments (char/short) are supplied
 * PPC-register-width pre-extended by the CALLER (caller-extends): the call
 * site writes the already sign-/zero-extended 32-bit value into the low 4
 * bytes of the slot, and thunks pass it through without re-extending.
 *
 * Pointer parameters and returns marshal as i32 (a 32-bit linear-memory
 * address); see dispatch_value_class in src/port_assembly_abi.py.
 */
#ifndef GF_DISPATCH_FRAME_H
#define GF_DISPATCH_FRAME_H

#include <stddef.h>

#define GF_DISPATCH_FRAME_VERSION 1
#define GF_DISPATCH_MAX_ARGS 16

#define GF_DISPATCH_CLASS_VOID 0
#define GF_DISPATCH_CLASS_I32 1
#define GF_DISPATCH_CLASS_I64 2
#define GF_DISPATCH_CLASS_F32 3
#define GF_DISPATCH_CLASS_F64 4

typedef union __gf_dispatch_slot {
  int i32;
  unsigned int u32;
  long long i64;
  unsigned long long u64;
  float f32;
  double f64;
  unsigned char raw[8];
} __gf_dispatch_slot;

typedef struct __gf_dispatch_frame {
  unsigned int arg_count; /* +0x00 */
  unsigned int ret_class; /* +0x04 */
  __gf_dispatch_slot ret; /* +0x08 */
  __gf_dispatch_slot args[GF_DISPATCH_MAX_ARGS]; /* +0x10 */
} __gf_dispatch_frame;

_Static_assert(sizeof(__gf_dispatch_slot) == 8, "gf dispatch slot is 8 bytes");
_Static_assert(offsetof(__gf_dispatch_frame, ret_class) == 0x04,
               "gf dispatch ret_class at +0x04");
_Static_assert(offsetof(__gf_dispatch_frame, ret) == 0x08,
               "gf dispatch return slot at +0x08");
_Static_assert(offsetof(__gf_dispatch_frame, args) == 0x10,
               "gf dispatch arg slots at +0x10");
_Static_assert(sizeof(__gf_dispatch_frame) == 0x90,
               "gf dispatch frame is 0x90 bytes");

#endif /* GF_DISPATCH_FRAME_H */
"""

# Chunk markers -- `// ==== 80003100  __check_pad3 ====` -- are the VERBATIM
# extraction format's per-definition address record, the same evidence the
# owner registry's _MARKER_RE validates on chunk sources. They are the
# authoritative in-artifact GC address for renamed symbols.
_MARKER_RE = re.compile(
    r"//\s*====\s*([0-9A-Fa-f]{8})\s+([A-Za-z_][A-Za-z0-9_]*)\s*===="
)
_ADDRESS_RE = re.compile(r"^[0-9a-f]{8}$")
_MASKED_RE = re.compile(
    r"/\*.*?\*/|//[^\n]*|\"(?:\\.|[^\"\\\n])*\"|'(?:\\.|[^'\\\n])*'", re.S
)
# Preprocessor directive lines (with continuations) are masked AFTER comments
# and strings: they never contain a definition head, and an unmasked
# `#include "gnt4_shim.h"` directly above the first definition would bleed
# into the return-spelling backscan (no ';' boundary between them).
_DIRECTIVE_RE = re.compile(r"^[ \t]*#[^\n]*(?:\\\n[^\n]*)*", re.M)
_RETURN_SPELLING_CHARS = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_* \t\r\n"
)


@dataclass(frozen=True)
class ThunkSignature:
    """One defined function's dispatch registration, fully derived."""

    symbol: str
    unit: str
    gc_address: str  # 8 lowercase hex digits
    address_source: str  # marker | symbol_name | owner_registry
    return_class: str  # void | i32 | i64 | f32 | f64
    param_classes: tuple[str, ...]
    return_spelling: str
    param_spellings: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "symbol": self.symbol,
            "unit": self.unit,
            "gc_address": self.gc_address,
            "address_source": self.address_source,
            "return_class": self.return_class,
            "param_classes": list(self.param_classes),
        }


@dataclass(frozen=True)
class CompanionProblem:
    """One reason the companion cannot be derived. The gate refuses on any."""

    unit: str
    symbol: str | None
    code: str
    detail: str


@dataclass
class CompanionResult:
    signatures: list[ThunkSignature] = field(default_factory=list)
    problems: list[CompanionProblem] = field(default_factory=list)


def _mask_comments_and_strings(text: str) -> str:
    """Replace comments/string literals with spaces, preserving offsets."""

    def blank(match: re.Match[str]) -> str:
        return "".join("\n" if ch == "\n" else " " for ch in match.group(0))

    return _DIRECTIVE_RE.sub(blank, _MASKED_RE.sub(blank, text))


def _brace_depths(masked: str) -> list[int]:
    depth = 0
    depths: list[int] = []
    for ch in masked:
        depths.append(depth)
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
    return depths


def _skip_space(masked: str, index: int) -> int:
    while index < len(masked) and masked[index] in " \t\r\n":
        index += 1
    return index


def _match_paren(masked: str, opening: int) -> int | None:
    depth = 0
    for index in range(opening, len(masked)):
        ch = masked[index]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return index
    return None


def _split_params(param_text: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in param_text:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return [" ".join(part.split()) for part in parts]


def find_definition_head(source_text: str, symbol: str) -> tuple[str, list[str]] | None:
    """(return spelling, raw parameter spellings) of `symbol`'s definition.

    Scans comment/string-masked text for a top-level `symbol ( ... ) {` site,
    reads the return spelling backwards from the symbol token (stopping at the
    previous statement/definition boundary) and splits the parameter list at
    top-level commas. Returns None when the unit contains no definition of the
    symbol (declarations end in `;` and never match).
    """
    masked = _mask_comments_and_strings(source_text)
    depths = _brace_depths(masked)
    for match in re.finditer(r"\b%s\b" % re.escape(symbol), masked):
        if depths[match.start()] != 0:
            continue
        opening = _skip_space(masked, match.end())
        if opening >= len(masked) or masked[opening] != "(":
            continue
        closing = _match_paren(masked, opening)
        if closing is None:
            continue
        body = _skip_space(masked, closing + 1)
        if body >= len(masked) or masked[body] != "{":
            continue
        start = match.start()
        while start > 0 and masked[start - 1] in _RETURN_SPELLING_CHARS:
            start -= 1
        return_spelling = " ".join(masked[start : match.start()].split())
        params = _split_params(masked[opening + 1 : closing])
        if params == [""]:
            params = []
        return return_spelling, params
    return None


def marker_addresses(source_text: str) -> tuple[dict[str, str], list[str]]:
    """{symbol: 8-hex address} from chunk markers, plus contradiction details."""
    addresses: dict[str, str] = {}
    contradictions: list[str] = []
    for match in _MARKER_RE.finditer(source_text):
        address, symbol = match.group(1).lower(), match.group(2)
        previous = addresses.get(symbol)
        if previous is not None and previous != address:
            contradictions.append(
                f"marker contradiction for {symbol}: {previous} vs {address}"
            )
            continue
        addresses[symbol] = address
    return addresses, contradictions


def _classify_param(param: str) -> str | None:
    """Marshalling class for one raw parameter spelling, or None."""
    text = " ".join(param.split())
    cls = dispatch_value_class(text)
    if cls is not None:
        return cls
    words = text.split()
    if len(words) >= 2:
        # `uint param_1` -- drop the trailing parameter NAME and retry.
        return dispatch_value_class(" ".join(words[:-1]))
    return None


def _classify_return(spelling: str) -> str | None:
    text = " ".join(spelling.split())
    if text in {"void", ""}:
        # Empty means the definition head carried no return spelling at all
        # (implicit int is not in this corpus); treat only explicit void here
        # and let the empty case fail below.
        return "void" if text == "void" else None
    return dispatch_value_class(text)


def resolve_gc_address(
    symbol: str,
    markers: Mapping[str, str],
    owner_addresses: Mapping[str, str],
) -> tuple[str | None, str, str | None]:
    """(address, source, problem detail) for one defined symbol.

    Authority order: the unit's own chunk marker (definitive, present per
    VERBATIM definition), the zz_/FUN_ name encoding, the owner registry's
    address field. A marker/name contradiction is a problem, never a pick;
    likewise, when the owner registry INDEPENDENTLY carries the symbol and
    disagrees with the resolved address, the pair is refused as a
    contradiction -- a stale re-extraction yields marker and name that are
    consistent with each other but wrong, and the registry is the only
    evidence that can catch it.
    """
    encoded = symbol_gc_address(symbol)
    marker = markers.get(symbol)
    if marker is not None and encoded is not None and marker != encoded:
        return None, "contradiction", (
            f"chunk marker says {marker} but the symbol name encodes {encoded}"
        )
    owner_raw = owner_addresses.get(symbol)
    owner = str(owner_raw).lower() if owner_raw is not None else None
    for address, source in (
        (marker, "marker"),
        (encoded, "symbol_name"),
        (owner, "owner_registry"),
    ):
        if address is None:
            continue
        address = str(address).lower()
        if _ADDRESS_RE.fullmatch(address) is None:
            return None, source, f"{source} address {address!r} is not 8 hex digits"
        if source != "owner_registry" and owner is not None and owner != address:
            return None, "contradiction", (
                f"{source} says {address} but the owner registry says {owner}"
            )
        return address, source, None
    return None, "none", (
        "no GC address derivable: no chunk marker, name encodes no address, "
        "owner registry has no record"
    )


def derive_window_signatures(
    units: Iterable[tuple[str, str, Iterable[str]]],
    owner_addresses: Mapping[str, str] | None = None,
) -> CompanionResult:
    """Derive every (unit, exported symbol) thunk signature for one window.

    `units` is [(unit_name, final_source_text, exported_symbols), ...] -- the
    source text must be the bytes the window actually compiles (derived
    sources on the canonicalization path), so thunk signatures match what the
    linker sees. Fails closed per symbol; the caller refuses on any problem.
    """
    owners = dict(owner_addresses or {})
    result = CompanionResult()
    by_address: dict[str, tuple[str, str]] = {}
    for unit_name, source_text, exports in units:
        exports = list(exports)
        markers, contradictions = marker_addresses(source_text)
        for detail in contradictions:
            result.problems.append(
                CompanionProblem(unit_name, None, "marker_contradiction", detail)
            )
        # Refusal gap (adversarial review F1): a function DEFINED in the unit
        # but absent from the export registration would get no thunk and no
        # problem record -- its GC address would route to the miss handler as
        # a wrong-behavior bridge call, exactly what the module docstring
        # forbids. Every marker symbol with a real definition head must be
        # registered, or the window refuses.
        registered = set(exports)
        for symbol in sorted(markers):
            if symbol in registered:
                continue
            if find_definition_head(source_text, symbol) is None:
                continue
            result.problems.append(
                CompanionProblem(
                    unit_name,
                    symbol,
                    "defined_not_registered",
                    f"{symbol} is defined in {unit_name} (marker "
                    f"{markers[symbol]}) but absent from the unit's exported "
                    "functions; unregistered, its GC address would route to "
                    "the miss handler as a wrong-behavior bridge call",
                )
            )
        for symbol in exports:
            head = find_definition_head(source_text, symbol)
            if head is None:
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "missing_definition",
                        f"exported symbol {symbol} has no definition in "
                        f"{unit_name}'s final source",
                    )
                )
                continue
            return_spelling, raw_params = head
            if any("..." in param for param in raw_params):
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "variadic_definition",
                        f"{symbol} is variadic; the uniform frame cannot "
                        "marshal an open argument list",
                    )
                )
                continue
            if raw_params == ["void"]:
                raw_params = []
            return_class = _classify_return(return_spelling)
            if return_class is None:
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "unknown_return_class",
                        f"{symbol} return spelling {return_spelling!r} has no "
                        "wasm value class",
                    )
                )
                continue
            param_classes: list[str] = []
            bad_param: str | None = None
            for param in raw_params:
                cls = _classify_param(param)
                if cls is None:
                    bad_param = param
                    break
                param_classes.append(cls)
            if bad_param is not None:
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "unknown_param_class",
                        f"{symbol} parameter {bad_param!r} has no wasm value "
                        "class",
                    )
                )
                continue
            if len(param_classes) > FRAME_MAX_ARGS:
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "arity_over_frame",
                        f"{symbol} has {len(param_classes)} parameters; the "
                        f"frame carries {FRAME_MAX_ARGS} slots",
                    )
                )
                continue
            address, source, detail = resolve_gc_address(symbol, markers, owners)
            if address is None:
                result.problems.append(
                    CompanionProblem(
                        unit_name, symbol, "address_underivable", detail or ""
                    )
                )
                continue
            claimed = by_address.get(address)
            if claimed is not None and claimed[0] != symbol:
                result.problems.append(
                    CompanionProblem(
                        unit_name,
                        symbol,
                        "address_collision",
                        f"GC address {address} already registered to "
                        f"{claimed[0]} ({claimed[1]})",
                    )
                )
                continue
            by_address[address] = (symbol, unit_name)
            result.signatures.append(
                ThunkSignature(
                    symbol=symbol,
                    unit=unit_name,
                    gc_address=address,
                    address_source=source,
                    return_class=return_class,
                    param_classes=tuple(param_classes),
                    return_spelling=return_spelling,
                    param_spellings=tuple(raw_params),
                )
            )
    result.signatures.sort(key=lambda item: (item.gc_address, item.symbol))
    return result


def _extern_declaration(signature: ThunkSignature) -> str:
    """A by-CLASS extern declaration of the real callee.

    The companion never includes unit headers (their declarations legitimately
    diverge per unit); it declares each callee with the spelling of its wasm
    value classes instead. That is wasm-signature-IDENTICAL to the true
    definition by construction -- object-level wasm signatures record value
    classes, not C spellings -- so the linker sees exact agreement.
    """
    return_type = (
        "void"
        if signature.return_class == "void"
        else _CLASS_C_TYPES[signature.return_class]
    )
    if signature.param_classes:
        params = ", ".join(_CLASS_C_TYPES[cls] for cls in signature.param_classes)
    else:
        params = "void"
    return f"extern {return_type} {signature.symbol}({params});"


def _thunk_name(signature: ThunkSignature) -> str:
    return f"__gf_thunk_{signature.gc_address}"


def _thunk_definition(signature: ThunkSignature) -> str:
    args = ", ".join(
        f"frame->args[{index}].{_CLASS_SLOT_MEMBERS[cls]}"
        for index, cls in enumerate(signature.param_classes)
    )
    call = f"{signature.symbol}({args})"
    lines = [
        f"/* {signature.symbol} @ 0x{signature.gc_address}"
        f" ({signature.address_source}): "
        f"{signature.return_class}({', '.join(signature.param_classes) or ''}) */",
        f"static int {_thunk_name(signature)}(int argptr) {{",
        "  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;",
    ]
    ret_macro = _CLASS_MACROS[signature.return_class]
    if signature.return_class == "void":
        lines += [
            f"  {call};",
            f"  frame->ret_class = {ret_macro};",
            "  frame->ret.i64 = 0;",
            "  return 0;",
        ]
    elif signature.return_class == "i32":
        lines += [
            f"  int result = {call};",
            f"  frame->ret_class = {ret_macro};",
            "  frame->ret.i64 = 0;",
            "  frame->ret.i32 = result;",
            "  return result;",
        ]
    elif signature.return_class == "i64":
        lines += [
            f"  long long result = {call};",
            f"  frame->ret_class = {ret_macro};",
            "  frame->ret.i64 = result;",
            "  return (int)result;",
        ]
    elif signature.return_class == "f32":
        lines += [
            f"  float result = {call};",
            f"  frame->ret_class = {ret_macro};",
            "  frame->ret.i64 = 0;",
            "  frame->ret.f32 = result;",
            "  return 0;",
        ]
    else:  # f64
        lines += [
            f"  double result = {call};",
            f"  frame->ret_class = {ret_macro};",
            "  frame->ret.f64 = result;",
            "  return 0;",
        ]
    lines.append("}")
    return "\n".join(lines)


def _emit_dispatch_at(count: int, trace: bool) -> list[str]:
    """`__gf_dispatch_at`: the entry the ROM's own lowered call sites use.

    Semantics are EXACTLY `__gf_dispatch`'s -- same table, same miss import,
    same arity ledger -- with two extra parameters that carry the CALL SITE and
    the per-argument class array the lowering filled. Without trace they are
    unused and the call is a straight forward to `__gf_dispatch`, so the
    lowered module behaves identically to an unobserved one.

    With trace, two declared imports bracket the dispatch. They are the whole
    point of the standard: `__gf_dispatch_enter` sees the site, the GC address
    the ROM resolved, the argument frame, the class array, and whether the
    address was found in this window's table; `__gf_dispatch_exit` sees the
    return the dispatch produced. A host observing those two imports observes
    exactly what a `call_indirect` on the module's own table hides.

    NOTE what trace does NOT change: the dispatch itself. The same thunk (or
    the same miss import) runs, with the same frame, in the same order. Trace
    adds observation, never behaviour -- so a traced run and an untraced run
    differ only in what the host is told.
    """
    lines: list[str] = [
        "",
        "/* Outbound entry for the ROM's own lowered `bctrl` call sites",
        " * (src/port_indirect_lowering.py). Same table, same miss import, plus",
        " * the originating SITE and the per-argument class array. */",
    ]
    if trace:
        lines += [
            f"extern void {TRACE_ENTER_IMPORT}(unsigned int site, unsigned int gc_addr,",
            "                                 int argptr, int classptr, int resolved);",
            f"extern void {TRACE_EXIT_IMPORT}(unsigned int site, unsigned int gc_addr,",
            "                                int argptr, int resolved, int result);",
        ]
    if count and trace:
        lines += [
            "static int __gf_dispatch_index(unsigned int gc_addr) {",
            "  unsigned int lo = 0;",
            f"  unsigned int hi = {count}u;",
            "  while (lo < hi) {",
            "    unsigned int mid = lo + (hi - lo) / 2u;",
            "    unsigned int probe = __gf_dispatch_addrs[mid];",
            "    if (probe == gc_addr) { return (int)mid; }",
            "    if (probe < gc_addr) { lo = mid + 1u; } else { hi = mid; }",
            "  }",
            "  return -1;",
            "}",
        ]
    lines += [
        f"int {DISPATCH_AT_EXPORT}(unsigned int site, unsigned int gc_addr, int argptr,",
        "                        int classptr) {",
    ]
    if not trace:
        lines += [
            "  (void)site;",
            "  (void)classptr;",
            f"  return {DISPATCH_EXPORT}(gc_addr, argptr);",
            "}",
        ]
        return lines
    if count:
        lines += [
            "  int idx = __gf_dispatch_index(gc_addr);",
            "  int result;",
            f"  {TRACE_ENTER_IMPORT}(site, gc_addr, argptr, classptr, idx >= 0);",
            "  if (idx >= 0) {",
            "    const __gf_dispatch_frame *frame =",
            "        (const __gf_dispatch_frame *)argptr;",
            "    if (frame->arg_count != __gf_dispatch_arity[idx]) {",
            "      __gf_arity_mismatch_count += 1u;",
            "    }",
            "    result = __gf_dispatch_thunks[idx](argptr);",
            "  } else {",
            f"    result = {MISS_IMPORT}(gc_addr, argptr);",
            "  }",
            f"  {TRACE_EXIT_IMPORT}(site, gc_addr, argptr, idx >= 0, result);",
            "  return result;",
            "}",
        ]
    else:
        lines += [
            "  int result;",
            f"  {TRACE_ENTER_IMPORT}(site, gc_addr, argptr, classptr, 0);",
            f"  result = {MISS_IMPORT}(gc_addr, argptr);",
            f"  {TRACE_EXIT_IMPORT}(site, gc_addr, argptr, 0, result);",
            "  return result;",
            "}",
        ]
    return lines


def emit_companion_source(signatures: list[ThunkSignature], *,
                          dispatch_at: bool = False,
                          trace: bool = False) -> str:
    """The companion translation unit. Deterministic for a given window.

    ``dispatch_at`` additionally emits `__gf_dispatch_at`, the outbound entry
    the indirect-call lowering rewrites ROM call sites into. ``trace`` (which
    implies it) makes that entry call the two declared observation imports.
    Both default OFF so a companion emitted without them is byte-identical to
    what this module has always produced.
    """
    if trace:
        dispatch_at = True
    ordered = sorted(signatures, key=lambda item: (item.gc_address, item.symbol))
    parts = [
        "/* gf_dispatch_companion.c -- address-keyed uniform-ABI dispatch",
        " * (docs/playable-port-design.md V4 H3).",
        " *",
        " * AUTO-GENERATED by the assembly gate (src/port_dispatch_companion.py)",
        " * for one N-unit window. DERIVED artifact: never hand-edited,",
        " * regenerated on every window link.",
        " *",
        " * One adapter thunk per function DEFINED in the window, all sharing",
        " * the canonical signature (i32 argptr) -> i32; the table maps GC code",
        " * address -> thunk; a lookup miss calls the declared host import",
        " * __gf_dispatch_miss (the H2/H3 bridge hook + bridged-call ledger),",
        " * never traps.",
        " */",
        '#include "gf_dispatch_frame.h"',
        "",
        "/* True callees, declared by wasm value class (see companion module",
        " * docstring): identical object-level wasm signatures by construction. */",
    ]
    parts.extend(_extern_declaration(item) for item in ordered)
    parts += [
        "",
        "/* Host bridge hook (H3): unknown gc_addr routes here and is ledgered",
        " * host-side. The wasm side only DECLARES it; a miss is a bridge call,",
        " * never a trap. */",
        f"extern int {MISS_IMPORT}(unsigned int gc_addr, int argptr);",
        "",
    ]
    parts.extend(_thunk_definition(item) + "\n" for item in ordered)
    count = len(ordered)
    parts += [
        "/* Arity ledger: a caller whose arg_count differs from the callee's",
        " * known arity still DISPATCHES (the register-residue class is",
        " * legitimate, V5 note 1) but the event is counted here for the host",
        " * to read. Ledger data only -- never a gate, never a trap. */",
        "static unsigned int __gf_arity_mismatch_count = 0u;",
        "",
        f"unsigned int {ARITY_EXPORT}(void) {{",
        "  return __gf_arity_mismatch_count;",
        "}",
        "",
    ]
    if count:
        parts += [
            "typedef int (*__gf_thunk_fn)(int argptr);",
            "",
            f"static const unsigned int __gf_dispatch_addrs[{count}] = {{",
        ]
        parts.extend(f"  0x{item.gc_address}u," for item in ordered)
        parts += [
            "};",
            "",
            f"static const __gf_thunk_fn __gf_dispatch_thunks[{count}] = {{",
        ]
        parts.extend(f"  {_thunk_name(item)}," for item in ordered)
        parts += [
            "};",
            "",
            f"static const unsigned char __gf_dispatch_arity[{count}] = {{",
        ]
        parts.extend(
            f"  {len(item.param_classes)}u, /* {item.symbol} */" for item in ordered
        )
        parts += [
            "};",
            "",
            f"int {DISPATCH_EXPORT}(unsigned int gc_addr, int argptr) {{",
            "  unsigned int lo = 0;",
            f"  unsigned int hi = {count}u;",
            "  while (lo < hi) {",
            "    unsigned int mid = lo + (hi - lo) / 2u;",
            "    unsigned int probe = __gf_dispatch_addrs[mid];",
            "    if (probe == gc_addr) {",
            "      const __gf_dispatch_frame *frame =",
            "          (const __gf_dispatch_frame *)argptr;",
            "      if (frame->arg_count != __gf_dispatch_arity[mid]) {",
            "        __gf_arity_mismatch_count += 1u;",
            "      }",
            "      return __gf_dispatch_thunks[mid](argptr);",
            "    }",
            "    if (probe < gc_addr) {",
            "      lo = mid + 1u;",
            "    } else {",
            "      hi = mid;",
            "    }",
            "  }",
            f"  return {MISS_IMPORT}(gc_addr, argptr);",
            "}",
        ]
    else:
        parts += [
            f"int {DISPATCH_EXPORT}(unsigned int gc_addr, int argptr) {{",
            f"  return {MISS_IMPORT}(gc_addr, argptr);",
            "}",
        ]
    if dispatch_at:
        parts.extend(_emit_dispatch_at(count, trace))
    return "\n".join(parts) + "\n"


def companion_evidence(
    signatures: list[ThunkSignature], companion_text: str, *,
    dispatch_at: bool = False, trace: bool = False
) -> dict[str, Any]:
    """The gate-result evidence block for one emitted companion."""
    if trace:
        dispatch_at = True
    extra: dict[str, Any] = {}
    if dispatch_at:
        extra["dispatch_at_export"] = DISPATCH_AT_EXPORT
    if trace:
        extra["trace_imports"] = [TRACE_ENTER_IMPORT, TRACE_EXIT_IMPORT]
        # An observed module is NOT a verified module. The observation imports
        # let a host see what the ROM dispatched to; whether that matches the
        # console is decided by run-dispatch.mjs against a console capture.
        extra["trace_claim"] = (
            "observation only: the trace imports report the site, resolved GC "
            "target, argument frame and return of every lowered indirect call. "
            "They make no comparison and establish no tier."
        )
    return {**extra, **{
        "frame_abi_version": FRAME_ABI_VERSION,
        "frame_header": FRAME_HEADER_FILENAME,
        "companion": COMPANION_FILENAME,
        "companion_sha256": hashlib.sha256(
            companion_text.encode("utf-8")
        ).hexdigest(),
        "dispatch_export": DISPATCH_EXPORT,
        "miss_import": MISS_IMPORT,
        "arity_export": ARITY_EXPORT,
        "functions": len(signatures),
        "table": [item.to_dict() for item in signatures],
    }}
